### ISSUE TITLE
Save lodestone id

### ISSUE THREAD

**Issue by Deckerz** [itinerare/ffxiv-tools#14]
When you use your lodestone id, to pull the xp data. I would be nice if the site cached the id for use next time you open the page.

**Comment by itinerare** [comment]
Hmm... I can see if that's practical to implement.

**Comment by Deckerz** [comment]
I should be very possible, just a client side cookie or something

**Comment by itinerare** [comment]
Well, yes-- that's why I said *practical* rather than possible.

**Comment by itinerare** [comment]
Was in fact pretty reasonable to implement. 👍 Have fun leveling!
